name: Deployment
on: [push, workflow_dispatch]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository
              uses: actions/checkout@v3
            - name: Install spcific node version
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
            - name: Run lint
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Get repository
              uses: actions/checkout@v3
            - name: Install spcific node version
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
            - name: test repository
              run: npm run test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get repository
              uses: actions/checkout@v3
            - name: Install spcific node version
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencies
              run: npm ci
            - name: install build
              run: npm run build
            - name: Deploy
              run: echo "Deploying"

