name: Deployment
on: [push, workflow_dispatch]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository
              uses: actions/checkout@v3
            - name: Install spcific node version
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
            - name: install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Run lint
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Get repository
              uses: actions/checkout@v3
            - name: Install spcific node version
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
            - name: install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: test repository
              id: run_test
              run: npm run test
            - name: Upload test report
              if: failure() && steps.run_test.outcome == 'failure'
              uses: actions/upload-artifacts@v3
              with:
                name: test-report
                path: test.json
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [12,14,16]
                operating-system: [ubuntu-latest, windows-latest]
                include:
                    - node-version: 18
                      operating-system: ubuntu-latest
                exclude:
                    - node-version: 12
                      operating-system: windows-latest                     
        needs: test
        runs-on: ${{matrix.operating-system}}
        outputs:
            script-file: ${{ steps.publish.outputs.script-filename }}
        steps:
            - name: Get repository
              uses: actions/checkout@v3
            - name: Install spcific node version
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-version}}
            - name: cache dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
            - name: install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: install build
              run: npm run build
            - name: Publish JS filename
              id: publish
              run: find dist/assets/*.js -type f -execdir echo "script-filename={}" >> $GITHUB_OUTPUT ';'
            - name:  upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: dist-files
                path: |
                  dist
                  package.json
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v3
              with:
                name: dist-files
            - name: output contents
              run: ls
            - name: output filename
              run: echo "${{ needs.build.outputs.script-file }}"
            - name: deploy
              run: echo "Deploying........"

    report:
        needs: [lint, deploy]
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: Output Information
              run: |
                echo "writing the report...."
                echo ${{ github.event}}


